# Classroom Attendance Prediction

## 1. Data Inspection

This notebook is used to inspect the attendance dataset,
understand its structure, identify missing values and
duplicates, and examine the available features before
data preprocessing.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_excel("D:/Classroom Attendance/data/raw/MCA_Attendance_Dataset_Faculty_ID_Encoded_300_Rows.xlsx")

In [3]:
df.head()

,Date,Day,Lecture Number,Start Time,Subject,Faculty ID,Semester,Branch,Section,Classroom,...,Attendance %,Previous Lecture Attendance,Practical/Theory,Test Week,Assignment Due,Holiday,Weather,Special Event,Lecture Occurred,Faculty Experience
0,2026-06-15,Monday,1,08:30,Mobile Application Development,F_001,3,MCA,A+B Combined,401,...,53.0,NaN,Practical,No,No,No,Rainy,No,Yes,10 years
1,2026-06-15,Monday,2,09:15,Mobile Application Development Hands-on,F_001,3,MCA,A+B Combined,403,...,92.0,53.0,Practical,No,No,No,Rainy,No,Yes,8 years
2,2026-06-15,Monday,3,10:15,Data Science & Machine Learning,F_002,3,MCA,A+B Combined,403,...,48.0,92.0,Practical,No,No,No,Rainy,No,Yes,10 years
3,2026-06-15,Monday,4,11:15,Innovation and Entrepreneurship Development,F_003,3,MCA,A+B Combined,403,...,79.0,48.0,Theory,No,Yes,No,Cloudy,No,Yes,9 years
4,2026-06-15,Monday,5,13:30,Cloud Computing Certification Training,F_004,3,MCA,A+B Combined,403,...,87.5,79.0,Practical,No,No,No,Rainy,No,Yes,8 years

## Dataset Dimensions

The shape of the dataset is checked to determine the number
of attendance records and features available for analysis.

In [4]:
df.shape

(300, 22)

## Column Names

The following columns are available in the attendance dataset.

In [5]:
df.columns

Index(['Date', 'Day', 'Lecture Number', 'Start Time', 'Subject', 'Faculty ID',
       'Semester', 'Branch', 'Section', 'Classroom', 'Total Enrolled Students',
       'Students Present', 'Attendance %', 'Previous Lecture Attendance',
       'Practical/Theory', 'Test Week', 'Assignment Due', 'Holiday', 'Weather',
       'Special Event', 'Lecture Occurred', 'Faculty Experience'],
      dtype='object')

## Dataset Information

The information below is used to examine the data types,
non-null values, and structure of the dataset.

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 22 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Date                         300 non-null    object
 1   Day                          300 non-null    object
 2   Lecture Number               300 non-null    int64
 3   Start Time                   300 non-null    object
 4   Subject                      300 non-null    object
 5   Faculty ID                   300 non-null    object
 6   Semester                     300 non-null    int64
 7   Branch                       300 non-null    object
 8   Section                      300 non-null    object
 9   Classroom                    300 non-null    int64
 10  Total Enrolled Students      300 non-null    int64
 11  Students Present             300 non-null    int64
 12  Attendance %                 300 non-null    float64
 13  Previous Lecture Attendance  247 non-null    float64
 14  Practical/Theory             300 non-null    object
 15  Test Week                    300 non-null    object
 16  Assignment Due               300 non-null    object
 17  Holiday                      300 non-null    object
 18  Weather                      300 non-null    object
 19  Special Event                300 non-null    object
 20  Lecture Occurred             300 non-null    object
 21  Faculty Experience           296 non-null    object
dtypes: float64(2), int64(5), object(15)
memory usage: 51.7+ KB

## Statistical Summary

Descriptive statistics are generated for numerical features
to understand their basic distribution.

In [7]:
df.describe()

,Lecture Number,Semester,Classroom,Total Enrolled Students,Students Present,Attendance %,Previous Lecture Attendance
count,300.000000,300.0,300.000000,300.0,300.000000,300.000000,247.000000
mean,3.416667,3.0,402.460000,200.0,110.853333,55.426667,56.587045
std,1.773944,0.0,0.889402,0.0,38.980209,19.490104,19.551462
min,1.000000,3.0,401.000000,200.0,12.000000,6.000000,6.000000
25%,2.000000,3.0,401.000000,200.0,93.000000,46.500000,46.500000
50%,3.000000,3.0,403.000000,200.0,96.000000,48.000000,49.000000
75%,5.000000,3.0,403.000000,200.0,141.000000,70.500000,72.500000
max,8.000000,3.0,403.000000,200.0,190.000000,95.000000,94.000000

## Missing Values

Missing values are identified before the data-cleaning stage.

In [8]:
df.isnull().sum()

Date                            0
Day                             0
Lecture Number                  0
Start Time                      0
Subject                         0
Faculty ID                      0
Semester                        0
Branch                          0
Section                         0
Classroom                       0
Total Enrolled Students         0
Students Present                0
Attendance %                    0
Previous Lecture Attendance    53
Practical/Theory                0
Test Week                       0
Assignment Due                  0
Holiday                         0
Weather                         0
Special Event                   0
Lecture Occurred                0
Faculty Experience              4
dtype: int64

## Duplicate Records

Duplicate records are checked to ensure that the dataset does
not contain repeated attendance observations.

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
df["Subject"].unique()

array(['Mobile Application Development',
       'Mobile Application Development Hands-on',
       'Data Science & Machine Learning',
       'Innovation and Entrepreneurship Development',
       'Cloud Computing Certification Training',
       'Software Testing & Quality Assurance', 'Soft Skill Session',
       'Soft Skill Evaluation', 'Lab Session', 'CI/CD Session',
       'Data Science & Machine Learning Hands-on',
       'Industry Readiness Program - Technical Mock Interview',
       'Industry Readiness Program - HR Mock Interview', 'AWS Training',
       'Regular Afternoon Session (Delayed)',
       'Project Milestone 1 Evaluation',
       'Principles of Cloud Management and Security',
       'Industry Readiness Program', 'Mini Project',
       'Software Testing & Quality Assurance Hands-on',
       'Talenlio ERP Hands-on', 'Selenium Hands-on',
       'Selenium Industry Input'], dtype=object)

In [11]:
df["Subject"].nunique()

23

In [12]:
df["Faculty ID"].unique()

array(['F_001', 'F_002', 'F_003', 'F_004', 'F_005', 'F_006', 'F_007',
       'F_008', 'F_009', 'F_010', 'F_011', 'F_000', 'F_012', 'F_013',
       'F_014', 'F_015'], dtype=object)

In [13]:
df["Branch"].unique()

array(['MCA'], dtype=object)

In [14]:
df["Section"].unique()

array(['A+B Combined'], dtype=object)

In [15]:
df["Classroom"].unique()

array([401, 403])

In [16]:
df["Attendance %"].describe()

count    300.000000
mean      55.426667
std       19.490104
min        6.000000
25%       46.500000
50%       48.000000
75%       70.500000
max       95.000000
Name: Attendance %, dtype: float64

In [17]:
print("Minimum Attendance:", df["Attendance %"].min())
print("Maximum Attendance:", df["Attendance %"].max())

Minimum Attendance: 6.0
Maximum Attendance: 95.0

## Conclusion

The attendance dataset was inspected for its dimensions,
column structure, data types, missing values, duplicate
records, categorical values, and attendance distribution.

The dataset will now be taken through the data-cleaning
and preprocessing stage.