## 2. Data Cleaning

In [1]:
import pandas as pd
import numpy as np

df = pd.read_excel("D:/Classroom Attendance/data/raw/MCA_Attendance_Dataset_Faculty_ID_Encoded_300_Rows.xlsx")

In [2]:
df["Date"] = pd.to_datetime(df["Date"])

In [3]:
df["Date"].dtype

dtype('<M8[ns]')

In [4]:
df.duplicated().sum()

np.int64(0)

In [5]:
df["Calculated Attendance %"] = (
    df["Students Present"] /
    df["Total Enrolled Students"]
) * 100

In [6]:
df[
    ["Students Present",
     "Total Enrolled Students",
     "Attendance %",
     "Calculated Attendance %"]
].head()

,Students Present,Total Enrolled Students,Attendance %,Calculated Attendance %
0,106,200,53.0,53.0
1,184,200,92.0,92.0
2,96,200,48.0,48.0
3,158,200,79.0,79.0
4,175,200,87.5,87.5

In [7]:
df[
    (df["Attendance %"] < 0) |
    (df["Attendance %"] > 100)
]

Empty DataFrame
Columns: [Date, Day, Lecture Number, Start Time, Subject, Faculty ID, Semester, Branch, Section, Classroom, Total Enrolled Students, Students Present, Attendance %, Previous Lecture Attendance, Practical/Theory, Test Week, Assignment Due, Holiday, Weather, Special Event, Lecture Occurred, Faculty Experience, Calculated Attendance %]
Index: []

[0 rows x 23 columns]

In [8]:
df[
    df["Students Present"] >
    df["Total Enrolled Students"]
]

Empty DataFrame
Columns: [Date, Day, Lecture Number, Start Time, Subject, Faculty ID, Semester, Branch, Section, Classroom, Total Enrolled Students, Students Present, Attendance %, Previous Lecture Attendance, Practical/Theory, Test Week, Assignment Due, Holiday, Weather, Special Event, Lecture Occurred, Faculty Experience, Calculated Attendance %]
Index: []

[0 rows x 23 columns]

In [9]:
df["Faculty Experience Years"] = (
    df["Faculty Experience"]
    .astype(str)
    .str.extract(r"(\d+)")
    .astype(float)
)

In [11]:
df[
    ["Faculty Experience",
     "Faculty Experience Years"]
].head()

  Faculty Experience  Faculty Experience Years
0           10 years                      10.0
1            8 years                       8.0
2           10 years                      10.0
3            9 years                       9.0
4            8 years                       8.0

In [12]:
df["Previous Lecture Attendance"].isnull().sum()

np.int64(53)

In [13]:
df["Previous Attendance Missing"] = (
    df["Previous Lecture Attendance"]
    .isna()
    .astype(int)
)

In [14]:
df["Previous Lecture Attendance"] = (
    df["Previous Lecture Attendance"]
    .fillna(df["Attendance %"].mean())
)

In [15]:
df.drop(
    columns=["Calculated Attendance %"],
    inplace=True
)

In [17]:
df.to_csv(
    "../data/cleaned/attendance_cleaned.csv",
    index=False
)